<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_antivirus_app_description'] = 'Антивирус с открытым исходным кодом и сканер вредоносного ПО для приложения "SMTP Mail Server". Это приложение отсканирует почту во время обмена сообщениями и выполнит функции, которые будут определены правилам сконфигурированными администратором.';
$lang['mail_antivirus_app_name'] = 'Антивирус почты';
$lang['mail_antivirus_mail_policies'] = 'Политика почты';
$lang['mail_antivirus_modify_gateway_antivirus_settings'] = 'Изменить параметры настройки шлюза антивируса';
