<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_antivirus_app_description'] = 'Otwarte skaner antywirusowy oraz antimalware dla serwerów pocztowych.';
$lang['mail_antivirus_app_name'] = 'Antywirus pocztowy';
$lang['mail_antivirus_mail_policies'] = 'Reguły poczty';
$lang['mail_antivirus_modify_gateway_antivirus_settings'] = 'Zmień ustawienia antywirusowe dla bramy sieciowej';
